# as65001 (the BGP router in AS 65001)
#as65001[image]=alpine:latest
as65001[image]=quay.io/openbgpd/openbgpd:latest
as65001[shell]=/bin/ash
as65001[0]=net_as1_as2
as65001[1]=net_as1_as3
as65001[2]=net_as1_as10
as65001[3]=net_as1_as4
as65001[4]=NET_IXP
as65001[5]=net_rpki
as65001[startup]=as65001.startup
as65001[bridged]=true
as65001[privileged]=true
as65001[entrypoint]="sleep infinity"
#as65001[mount]=configs/as65001.conf:/etc/bgpd/bgpd.conf
#net-ixp is ashared layer-2 network so all connected to this are in the same subnet
#all member share common peering LAN

# as65002
as65002[image]=quay.io/openbgpd/openbgpd:latest
as65002[shell]=/bin/ash
as65002[0]=net_as1_as2
as65002[startup]=as65002.startup
as65002[entrypoint]="sleep infinity"
as65002[1]=net_as99_as2
as65002[2]=net_rpki

# as65003
as65003[image]=quay.io/openbgpd/openbgpd:latest
as65003[shell]=/bin/ash
as65003[0]=net_as1_as3
as65003[startup]=as65003.startup
as65003[entrypoint]="sleep infinity"

# as65010
as65010[image]=quay.io/openbgpd/openbgpd:latest
as65010[shell]=/bin/ash
as65010[0]=net_as1_as10
as65010[startup]=as65010.startup
as65010[entrypoint]="sleep infinity"

# as65099 (malicious attacker)
as65099[image]=quay.io/openbgpd/openbgpd:latest
as65099[shell]=/bin/ash
as65099[0]=net_as4_as99
as65099[startup]=as65099.startup
as65099[entrypoint]="sleep infinity"
as65099[1]=net_as99_as2
as65099[2]=net_rpki

# as65004 (additional transit)
as65004[image]=quay.io/openbgpd/openbgpd:latest
as65004[shell]=/bin/ash
as65004[0]=net_as1_as4
as65004[1]=net_as4_as99
as65004[2]=net_rpki
as65004[startup]=as65004.startup
as65004[entrypoint]="sleep infinity"
as65004[shared]=1
# IXP route server (as65000)
as65000[image]=quay.io/openbgpd/openbgpd:latest
as65000[shell]=/bin/ash
as65000[0]=NET_IXP
as65000[1]=net_rpki
as65000[startup]=as65000.startup
as65000[entrypoint]="sleep infinity"
as65000[shared]=1

# as65005 (extra at IXP)
as65005[image]=quay.io/openbgpd/openbgpd:latest
as65005[shell]=/bin/ash
as65005[0]=NET_IXP
as65005[startup]=as65005.startup
as65005[entrypoint]="sleep infinity"

# BGP Alerter
#bgpalerter[image]=nttgin/bgpalerter:latest
#bgpalerter[shell]=/bin/ash
#bgpalerter[0]=net_ixp
#bgpalerter[mount]=bgpalerter/config.yml:/opt/bgpalerter/volume/config.yml
#bgpalerter[mem]=4096

# Rpki-client - single combined mount line
rpki_validator[image]=kathara/rpki-client:latest
rpki_validator[shell]=/bin/sh
rpki_validator[0]=net_rpki
rpki_validator[startup]=rpki_validator.startup
rpki_validator[bridged]=true
rpki_validator[privileged]=true
rpki_validator[user]=0
rpki_validator[entrypoint]="sleep infinity"
#routinator[cap_add]=NET_ADMIN,NET_RAW,SYS_ADMIN
#routinator[exec]="bin/sh /routinator.startup"
#to overrises the internal tini entrypoint
