AS 65002
router-id 2.2.2.2
listen on 0.0.0.0

include "/shared/rpki.conf"

network 172.16.2.0/24
neighbor 10.0.12.1 {
 remote-as 65001 
 role customer
}

neighbor 10.0.19.1 {
  remote-as 65099
  role customer 
}



match from any ovs valid set localpref 200
match from any avs valid set localpref 200

deny from any ovs invalid
# deny from any avs invalid

allow from any
allow to any
