AS 65000
router-id 16.16.16.16
#route-collector yes
listen on 0.0.0.0

socket "/var/run/bgpd.sock"

#Import the Validator data
include "/shared/rpki.conf"

neighbor 10.0.10.1 {
 remote-as 65001
 role rs             
# description "AS65001 - Main Transit"
}


neighbor 10.0.10.3 {
 remote-as 65005
 role rs
 #description "AS65005 - IXP Member"
}


#RPKI security policy
match from any ovs valid avs valid set localpref 200

#enforcement drop invalids at the IXP level
deny from any ovs invalid
deny from any avs invalid

allow from any
allow to any
