AS 65001
router-id 1.1.1.1
listen on 0.0.0.0

#creats a control socket so i can you bgpctl commands
socket "/var/run/bgpd.sock"

# Import the RPKI data from the shared volume
# This file contains the 'roa-set' created by rpki-client
include "/shared/rpki.conf"

neighbor 10.0.12.2 {
 remote-as 65002 
 role provider
}
neighbor 10.0.13.2 {
 remote-as 65003 
 role provider
}
neighbor 10.0.110.2 {
 remote-as 65010 
 role provider
}
neighbor 10.0.14.2 { 
 remote-as 65004 
 role provider
}
neighbor 10.0.10.254 {
 remote-as 65000
 role rs-client
# announce all
}

#security enforcment
deny from any ovs invalid
deny from any avs invalid

#RPKI validation policies

# 1. Match and Tag
match from any ovs valid set localpref 200
match from any avs valid set localpref 200
#match from any ovs unknown set localpref 150



# 2. Default filter
allow from any
allow to any 



allow to 10.0.10.254
