AS 65099
router-id 99.99.99.99


include "/shared/rpki.conf"

# Attacking AS65002's prefix


network 172.16.2.0/25
network 172.16.3.1/32

neighbor 10.0.99.1 {
 remote-as 65004
 role customer 
}

neighbor 10.0.19.2 {
 remote-as 65002
 role provider

}

#match from 10.0.99.1 set localpref 300
#allow to 10.0.19.2
allow from any

allow to any

