AS 65004
router-id 4.4.4.4
listen on 0.0.0.0
socket "/var/run/bgpd.sock"

network 192.16.2.0/24
# Include the RPKI/ASPA data
include "/shared/rpki.conf"


neighbor 10.0.14.1 {
 remote-as 65001
 role customer
}
neighbor 10.0.99.2 {
 remote-as 65099
 role provider
}


# BLOCKING FILTER: Active Enforcement
# This will drop the hijack before it even enters your RIB
deny quick from any ovs invalid
deny quick from any avs invalid

# Standard policy for Valid/Found
match from any ovs valid set localpref 150
match from any avs valid set localpref 150

allow from any
allow to any


